# Generated by Django 4.2.4 on 2023-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='bio',
            field=models.TextField(help_text='Enter something about you', max_length=1000, null=True),
        ),
    ]
